Repository woocommerce/navigation, pull requests merged in 2020-07, with the labels that each got.

#12 Folders: Match folder structure to wc-admin
  client/index.js
  client/index.scss
  webpack.config.js
Labels: [status] Needs Review

#15 Add code editor integration
  .editorconfig
  .eslintrc
  .prettierrc.js
  package-lock.json
  package.json
Labels: [status] Ready to Merge

#17 Migrate existing POC work from WCA
  client/Navigation.js
  client/index.js
  client/index.scss
  client/stylesheets/_colors.scss
  client/stylesheets/_variables.scss
  client/stylesheets/index.scss
  src/CoreMenu.php
  src/Loader.php
  src/Menu.php
  src/Screen.php
Labels: [status] Ready to Merge

#20 Add php linting
  package.json
  phpcs.xml.dist
  src/CoreMenu.php
  src/FeaturePlugin.php
  src/Loader.php
  src/Menu.php
Labels: [status] Ready to Merge

#19 Add PHP unit test plumbing
  bin/install-wp-tests.sh
  bin/phpunit.sh
  navigation.php
  phpunit.xml.dist
  tests/bootstrap.php
  tests/sample-test.php
Labels: [status] Needs feedback

#22 Add base styles
  client/stylesheets/_colors.scss
  client/stylesheets/_mixins.scss
  client/stylesheets/index.scss
  package-lock.json
  package.json
Labels: [status] Ready to Merge

#23 Fix dependencies
  client/Navigation.js
  client/index.js
  src/Loader.php
Labels: [status] Needs feedback

#26 Add pre-commit and pre-push git hooks
  .eslintrc
  .nvmrc
  .stylelintrc.json
  client/test/sample-test.js
  package-lock.json
  package.json
Labels: [status] Ready to Merge

#31 Fix script dependencies
  client/Navigation.js
  src/Loader.php
  src/Menu.php
  tests/sample-test.php
Labels: [status] Ready to Merge

#33 Add function to register post type
  src/CoreMenu.php
  src/Menu.php
  src/Screen.php
Labels: [status] Ready to Merge

#35 Update menu items to flat structure
  client/Navigation.js
  src/Menu.php
  tests/menu.php
Labels: [status] Ready to Merge

#39 Add tests for Screen class
  src/Menu.php
  src/Screen.php
  tests/screen.php
Labels: [status] Ready to Merge

#42 Include `tests/` in PHPCompatibility phpcs rule
  phpcs.xml.dist
Labels: [status] Ready to Merge

#43 Update menu function args to an array
  client/Navigation.js
  src/CoreMenu.php
  src/Menu.php
  src/Screen.php
  tests/menu.php
  tests/screen.php
Labels: [status] Needs feedback, [status] Ready to Merge

#48 Register store for menu items
  client/Navigation.js
  client/store/action-types.js
  client/store/actions.js
  client/store/constants.js
  client/store/index.js
  client/store/reducer.js
  client/store/selectors.js
  client/store/test/reducer.js
  package-lock.json
  package.json
Labels: [status] Ready to Merge

#50 Fix non-boolean migrate properties
  src/CoreMenu.php
Labels: [status] Ready to Merge

#53 Check for dom root element before rendering
  client/index.js
Labels: [status] Ready to Merge

#30 Add Travis
  .travis.yml
  bin/js_lint_test.sh
  bin/phpcs.sh
  bin/phpunit.sh
  bin/travis.sh
  client/navigation.js
  package-lock.json
Labels: [status] Needs feedback, [status] Ready to Merge

#51 Allow multiple menus and flatten menu items
  client/store/action-types.js
  client/store/actions.js
  client/store/reducer.js
  client/store/selectors.js
  client/store/test/reducer.js
  src/CoreMenu.php
  src/Menu.php
Labels: [status] Ready to Merge
